apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: sentinel-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: api-gateway-secrets
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@cloud-sentinel-prod-db.ccl08080yhkx.us-east-1.rds.amazonaws.com:5432/cloud_sentinel"
        REDIS_URL: "redis://redis.sentinel-apps.svc.cluster.local:6379"
        JWT_SECRET_KEY: "{{ .jwt_secret }}"
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-9f7d3302-f771-418d-94e7-89cbf4ad279b
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-9f7d3302-f771-418d-94e7-89cbf4ad279b
        property: password
    - secretKey: jwt_secret
      sourceRef:
        storeRef:
          name: aws-parameter-store-production
          kind: ClusterSecretStore
      remoteRef:
        key: /sentinel/production/api-gateway/jwt-secret
