apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway
  - frontend
  - redis
  - traffic-generator

images:
  - name: cloud-sentinel/gateway:latest
    newName: 434504869339.dkr.ecr.us-east-1.amazonaws.com/cloud-sentinel-prod-api-gateway
    newTag: git-edffd6a
  - name: cloud-sentinel/frontend:latest
    newName: 434504869339.dkr.ecr.us-east-1.amazonaws.com/cloud-sentinel-prod-frontend
    newTag: git-edffd6a
