apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: sentinel-ops
  annotations:
    # Grants the ExternalSecrets operator strict access to AWS Parameter Store/Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/SentinelExternalSecretsRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-backup-sa
  namespace: sentinel-ops
  annotations:
    # Grants Velero strict write-only access to the S3 Disaster Recovery bucket
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/SentinelVeleroBackupRole
