global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # The FastAPI Backend Gateway
  - job_name: 'sentinel-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8000']

  # Host machine metrics (CPU, RAM, Disk)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Cache metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
