apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: taints-tolerations-patch.yaml
    target:
      kind: StatefulSet
      name: prometheus-sentinel-prometheus
      namespace: sentinel-monitoring

commonLabels:
  platform.sentinel.io/component: sre-node-governance
