apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../workloads
  - ../../networking/routes

patches:
  - path: patches/env-patch.yaml

namePrefix: prod-
commonLabels:
  env: production

images:
  - name: cloud-sentinel/gateway:latest
    newName: 434504869339.dkr.ecr.us-east-1.amazonaws.com/cloud-sentinel-prod-api-gateway
    newTag: git-818e1b5
  - name: cloud-sentinel/frontend:latest
    newName: 434504869339.dkr.ecr.us-east-1.amazonaws.com/cloud-sentinel-prod-frontend
    newTag: git-818e1b5
  - name: cloud-sentinel/traffic-generator:latest
    newName: 434504869339.dkr.ecr.us-east-1.amazonaws.com/cloud-sentinel-prod-traffic-generator
    newTag: git-818e1b5
