apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki.yaml
  - promtail-daemonset.yaml
  - service.yaml

commonLabels:
  platform.sentinel.io/component: centralized-logging
