apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - service-monitors.yaml
  - cluster-telemetry.yaml

commonLabels:
  platform.sentinel.io/component: prometheus-stack
