apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: sentinel-monitoring
  labels:
    platform.sentinel.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  namespaceSelector:
    matchNames:
      - sentinel-apps
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-monitor
  namespace: sentinel-monitoring
  labels:
    platform.sentinel.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - sentinel-ingress
  endpoints:
    - port: metrics
      interval: 15s
