apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-monitoring-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/charan21042005/cloud-sentinel-platform.git'
    targetRevision: HEAD
    path: infrastructure/kubernetes/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
