"""enterprise_incident_intelligence_architecture

Revision ID: 7de11d9f64a4
Revises: eac9a617da91
Create Date: 2026-05-12 13:27:37.124659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7de11d9f64a4'
down_revision: Union[str, None] = 'eac9a617da91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_events_timestamp'), 'incident_events', ['timestamp'], unique=False)
    op.add_column('incidents', sa.Column('fingerprint', sa.String(length=255), server_default='legacy_alert_chain', nullable=False))
    op.add_column('incidents', sa.Column('source', sa.String(length=100), server_default='Prometheus', nullable=False))
    op.add_column('incidents', sa.Column('affected_service', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('incidents', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('incidents', sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('incidents', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('incidents', sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('incidents', sa.Column('event_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('incidents', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('incidents', sa.Column('correlation_window', sa.Integer(), server_default='1800', nullable=False))
    op.add_column('incidents', sa.Column('escalation_level', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_incidents_triggered_at'), 'incidents', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_triggered_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_column('incidents', 'escalation_level')
    op.drop_column('incidents', 'correlation_window')
    op.drop_column('incidents', 'last_seen_at')
    op.drop_column('incidents', 'event_count')
    op.drop_column('incidents', 'occurrence_count')
    op.drop_column('incidents', 'raw_payload')
    op.drop_column('incidents', 'annotations')
    op.drop_column('incidents', 'labels')
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'acknowledged_at')
    op.drop_column('incidents', 'triggered_at')
    op.drop_column('incidents', 'affected_service')
    op.drop_column('incidents', 'source')
    op.drop_column('incidents', 'fingerprint')
    op.drop_index(op.f('ix_incident_events_timestamp'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_id'), table_name='incident_events')
    op.drop_table('incident_events')
    # ### end Alembic commands ###
