"""add_user_security_fields

Revision ID: eac9a617da91
Revises: 1b85dcc112f3
Create Date: 2026-05-11 11:30:04.170744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eac9a617da91"
down_revision: Union[str, None] = "1b85dcc112f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=False)
    )
    op.add_column("users", sa.Column("role", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "role")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
