apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-sealed-secret-template
  namespace: sentinel-apps
  labels:
    platform.sentinel.io/governance: sealed-secrets
spec:
  encryptedData:
    DATABASE_URL: "AgB5/XXXXX/YYYYY/ZZZZZ/placeholder-encrypted-blob-string"
  template:
    metadata:
      name: api-gateway-secret
      labels:
        app.kubernetes.io/name: api-gateway
    type: Opaque
