apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: sentinel-apps
  labels:
    app.kubernetes.io/name: api-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-dashboard-sa
  namespace: sentinel-apps
  labels:
    app.kubernetes.io/name: frontend-dashboard
automountServiceAccountToken: false
