apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: sentinel-apps
  labels:
    app.kubernetes.io/name: frontend
data:
  NEXT_PUBLIC_API_URL: "http://sentinel.ops.internal/api"
  NEXT_PUBLIC_WS_URL: "ws://sentinel.ops.internal/ws"
  NODE_ENV: "production"
