apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: sentinel-apps
spec:
  minAvailable: 66%
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-dashboard-pdb
  namespace: sentinel-apps
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-dashboard
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ingress-controller-pdb
  namespace: sentinel-ingress
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
